use work;
EXPLAIN SELECT e.FIRST_NAME, e.LAST_NAME, p.NAME FROM employee e
STRAIGHT_JOIN position p ON p.POSITION_ID = e.POSITION_ID;

EXPLAIN SELECT e.FIRST_NAME, e.LAST_NAME, p.NAME FROM employee e
INNER JOIN position p ON p.POSITION_ID = e.POSITION_ID;

EXPLAIN SELECT e.FIRST_NAME, e.LAST_NAME, p.NAME FROM employee e, position p
WHERE p.POSITION_ID = e.POSITION_ID;

###  Lecture 21  ###
CREATE DATABASE shop;
use shop;
CREATE TABLE USER
(
    USER_ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(20),
    LOGIN VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(25) NOT NULL,
    BIRTHDAY DATE,
    STATUS CHAR(10) DEFAULT 'ACTIVE' NOT NULL
);
CREATE UNIQUE INDEX USER_LOGIN_uindex ON USER (LOGIN);

CREATE TABLE ITEM
(
    ITEM_ID INT(7) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    SUPPLIER VARCHAR(20),
    MODEL VARCHAR(15),
    PRICE DEC NOT NULL
);

CREATE TABLE `ORDER`
(
    ORDER_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `DATE` DATETIME NOT NULL,
    USER_ID INT(10) NOT NULL,
    ITEM_ID INT(11) NOT NULL,
    QUANTITY INT(5) DEFAULT 1 NOT NULL,
    STATUS CHAR(10) DEFAULT 'NEW' NOT NULL
);

ALTER TABLE shop.`ORDER`
ADD CONSTRAINT user_fk
FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID);

CREATE TABLE shop.ORDER_ITEM
(
    ORDER_ID INT(11) NOT NULL,
    ITEM_ID INT(7) NOT NULL,
    CONSTRAINT ORDER_ITEM_pk PRIMARY KEY (ORDER_ID, ITEM_ID),
    CONSTRAINT ORDER_fk FOREIGN KEY (ORDER_ID) REFERENCES `ORDER` (ORDER_ID),
    CONSTRAINT ITEM_fk FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID)
);

INSERT INTO ITEM (SUPPLIER, MODEL, PRICE) VALUES
    ('Bosch', 'GBH 2-24 D', 259.0),
    ('Bosch', 'GBH 2-26 DFR', 367.0),
    ('Bosch', 'GBH 2-28 DFV', 375.80),
    ('Bosch', 'GBH 2-24 DRE', 309.0);

CREATE PROCEDURE getItemPrice(IN itemId INT, OUT itemPrice DECIMAL(10))
    BEGIN
        SELECT PRICE
        INTO itemPrice
        FROM ITEM
        WHERE ITEM_ID = itemId;
    END